version: "3.9"
services:
  server:
    image: jacopofar/demo-rest-server

  test:
    build: demo-REST-server-test
    environment:
      SERVER_URL: http://server:7000
    depends_on:
      - server
